### PR TITLE
Few Pics Added to Screenshot Page

### PR DESCRIPTION
**Pull request by aleone2**
Evidence of Work

### CODE REVIEW

**Comment by chase-saca** [comment]
What are the little stars on the left corners of the screenshots? Are they favorited buttons? Nothing happens when I press on them. Other than that the layout looks good!

**Comment by aleone2** [comment]
@chase-saca changed the Icon type to make it non-clickable and the Icon itself to a fish! Thought it was fitting

**Review by chase-saca — APPROVED** [review]
Looks good - I like the fish!

**Comment by aleone2** [comment]
[Update/Add Screenshots](https://trello.com/c/PXAoR70E/47-update-add-screenshots)

**Pull request merged**
