### PR TITLE
Contribution page

### PR DESCRIPTION
**Pull request by chase-saca**
The contribution page is complete. I included a list of ways to contribute, as well as the development / branch workflow necessary to contribute code. I think that covers it, but let me know if there is anything else! 

Screen Shot 2022-02-06 at 9 02 03 PM
Screen Shot 2022-02-06 at 9 02 24 PM

### CODE REVIEW

**Comment by chase-saca** [comment]
Full Page Zoomed Out:

Screen Shot 2022-02-06 at 9 03 48 PM

**Comment by chase-saca** [comment]
[Website Contribution Page](https://trello.com/c/6BlIV4g0/23-website-contribution-page)

**Comment by chase-saca** [comment]
Full Page Zoomed Out:

Screen Shot 2022-02-06 at 9 11 16 PM

**Comment by chase-saca** [comment]
I changed all of the contribution methods to be buttons with links that send you to the necessary page to contribute.

**Review by rpmccarter — APPROVED** [review]
Looks great, thanks for the links!

**Pull request merged**
