### PR TITLE
Screenshots Page

### PR DESCRIPTION
**Pull request by chase-saca**
I set up the container so that, in the future, we can simply add images to the image list easily. The container is dynamic in that it changes with the change in width and height of the screen. Furthermore, whenever a new image is added, the images' order is moved around so they fit nicely in the box. Here is an example with random stock images:

Screen Shot 2022-02-08 at 11 23 16 AM

Screen Shot 2022-02-08 at 11 23 27 AM

The order they appear in is NOT the order of the list. This is the best structure for unedited, uncropped images.

### CODE REVIEW

**Comment by chase-saca** [comment]
I can either take away all photos, leave the fun stock photos, OR do photos that we have thus far from the milestones. Maybe like the blob fishes, the walkthrough diagram, etc. Let me know what you guys think.

**Comment by chase-saca** [comment]
[Website Screenshot / GIF Page](https://trello.com/c/z1vTA1pQ/25-website-screenshot-gif-page)

**Review by rpmccarter — APPROVED** [review]
Looks good to me, love the column layout

**Comment by chase-saca** [comment]
Page Placeholder:

Screen Shot 2022-02-08 at 12 46 25 PM

To add screenshots in the future, simply add in the images like below. I kept this comment in the code so that it's easy for the first person who adds screenshots.

Screen Shot 2022-02-08 at 12 46 52 PM

**Comment by chase-saca** [comment]
My screenshots branch was behind the commits for the about and installation pages, and I needed the photos and code from them. I rebased the branch to get the code/photos from main, but it ended up taking all of the commits from the branch rather than squashing them... We should still be fine to merge this branch, but that's why it says 11 commits rather than like 2 lol.

**Review by aleone2 — APPROVED** [review]

**Pull request merged**
